### ISSUE TITLE
Automatically detect new package versions and publish to anaconda cloud

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/vendored-conda-builds#1]
Pretty sure it should be possible to use the anaconda cloud API and PyPI API to detect when a new package version has been published and to then build and publish that new version automatically to our Anaconda cloud channel (without needing our intervention) by configuring the GitHub action to run on a schedule (daily for example) as well as on repo push to achieve this.

**Comment by chrisjbillington** [comment]
We could use the APIs, or just the brute force approach of having this run daily or weekly - anaconda upload can ignore duplicate uploads by default so it will only update what needs updating.

At the moment I've got it configured to upload to the test label on push, and the main label on tag. The idea being you might be messing around with build configuration and not want to upload the results the main label.

So if we ran it on a timer, the job should probably check out the most recently tagged commit for the job.

I'll look into setting that up.

**Comment by chrisjbillington** [comment]
This is implemented, running weekly. No API use to actually check which versions need updating, just brute-forcing it for now.

**Comment by rpanderson** [comment]
> At the moment I've got it configured to upload to the test label on push, and the main label on tag. The idea being you might be messing around with build configuration and not want to upload the results the main label.

So this mirrors our publishing on PyPI and TestPyPI?

**Comment by chrisjbillington** [comment]
> So this mirrors our publishing on PyPI and TestPyPI?

Yep! For pushing anyway.

The scheduled job checks out the most recent tag before running the build, so it's only ever uploading to the real label based on the last tagged commit

I'm just tagging with the current date since version numbers here are pretty meaningless since the tag is just to trigger the CI.
